+check_response

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -203,7 +203,7 @@ jobs:
           SERVICE_NAME=$(terraform output -raw service_name)
           echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT
 
-  check:
+  check_image:
     needs: 
       - task
       - service
@@ -249,3 +249,35 @@ jobs:
           else
             echo "Image matched: ${{ env.CURRENT_IMAGE }}"
           fi
+
+  check_response:
+    needs: 
+      - network
+      - service
+    runs-on: ubuntu-latest
+    steps:
+      - name: Make API request
+        id: curl_request
+        run: |
+          RESPONSE=$(curl -s ${{ needs.network.outputs.api_invoke_url}}/host)
+          echo "Response: $RESPONSE"
+          echo "$RESPONSE" | jq
+      
+      - name: Assert API response contains expected fields
+        run: |
+          RESPONSE=$(curl -s ${{ needs.network.outputs.api_invoke_url}}/host)
+          echo "$RESPONSE" | jq
+          
+          # Extract values from response
+          MESSAGE=$(echo "$RESPONSE" | jq -r '.message')
+          IMAGE_URI=$(echo "$RESPONSE" | jq -r '.imageUri')
+          HOSTNAME=$(echo "$RESPONSE" | jq -r '.hostname')
+
+          # Check if expected fields exist
+          if [[ "$MESSAGE" == "null" || "$IMAGE_URI" == "null" || "$HOSTNAME" == "null" ]]; then
+            echo "Error: Response does not contain expected fields."
+            exit 1
+          else
+            echo "API response contains all expected fields."
+          fi
+        
