yaml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,9 @@
 name: Deploy
 
 on:
-  push:
-    branches:
-      - 'blue-green-deploy'
+  # push:
+  #   branches:
+  #     - 'blue-green-deploy'
   workflow_dispatch:
 
 permissions:
@@ -23,6 +23,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       TF_VAR_FILE: tf/variables.tfvars
+      APP_SPEC_FILE: appspec.yaml
     steps:
       - uses: actions/checkout@v4
       - uses: aws-actions/configure-aws-credentials@v4
@@ -54,11 +55,14 @@ jobs:
       # Step 3: Replace placeholders in the appspec.json file
       - name: Prepare AppSpec File
         run: |
-          sed -i 's|{{TASK_VERSION}}|${{ needs.code.outputs.task_definition_revsion }}|g' appspec.json
-          sed -i 's|{{TASK_DEFINITION_ARN}}|${{ needs.code.outputs.task_definition_arn }}|g' appspec.json
-          sed -i 's|{{CONTAINER_NAME}}|${{ steps.read-vars.outputs.project_name }}|g' appspec.json
-          sed -i 's|{{CONTAINER_PORT}}|${{ steps.read-vars.outputs.container_port }}|g' appspec.json
-          cat appspec.json
+          sed -i 's|{{TASK_VERSION}}|${{ needs.code.outputs.task_definition_revision }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{TASK_DEFINITION_ARN}}|${{ needs.code.outputs.task_definition_arn }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{CONTAINER_NAME}}|${{ steps.read-vars.outputs.project_name }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{CONTAINER_PORT}}|${{ steps.read-vars.outputs.container_port }}|g' ${{ env.APP_SPEC_FILE }}
+          cat ${{ env.APP_SPEC_FILE }}
+
+      - name: Upload yaml to s3
+        run: aws s3 cp ${{ env.APP_SPEC_FILE }} s3://${{ needs.code.outputs.app_specs_bucket}}/${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}"
 
       # Step 4: Create CodeDeploy Deployment
       - name: Create CodeDeploy Deployment
@@ -67,53 +71,48 @@ jobs:
           GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
         run: |
           echo "Creating CodeDeploy deployment"
-          APP_SPEC_CONTENT=$(cat appspec.json | jq -c .)
-          ESCAPED_APP_SPEC_CONTENT=$(echo "$APP_SPEC_CONTENT" | sed 's/"/\\"/g')
-          
-          echo "{\"revisionType\":\"AppSpecContent\",\"appSpecContent\":{\"content\":$ESCAPED_APP_SPEC_CONTENT}}" > revision.json
-
           aws deploy create-deployment \
             --application-name "$APP_NAME" \
             --deployment-group-name "$GROUP_NAME" \
-            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
-            --revision "file://revision.json" \
+            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
+            --revision "revisionType=S3,s3Location={\"bucket\":\"${{ needs.code.outputs.app_specs_bucket}}\",\"key\":\"${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}\",\"bundleType\":\"YAML\"}" \
             --region ${{ vars.AWS_REGION }}
         
-      # Step 5: Monitor Deployment Status
-      - name: Monitor Deployment Status
-        env:
-          APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
-          GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
-        run: |
-          echo "Monitoring CodeDeploy deployment status"
-          DEPLOYMENT_ID=$(aws deploy list-deployments \
-            --application-name "$APP_NAME" \
-            --deployment-group-name "$GROUP_NAME" \
-            --region ${{ vars.AWS_REGION }} \
-            --max-items 1 \
-            --query 'deployments[0]' --output text)
+      # # Step 5: Monitor Deployment Status
+      # - name: Monitor Deployment Status
+      #   env:
+      #     APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
+      #     GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
+      #   run: |
+      #     echo "Monitoring CodeDeploy deployment status"
+      #     DEPLOYMENT_ID=$(aws deploy list-deployments \
+      #       --application-name "$APP_NAME" \
+      #       --deployment-group-name "$GROUP_NAME" \
+      #       --region ${{ vars.AWS_REGION }} \
+      #       --max-items 1 \
+      #       --query 'deployments[0]' --output text)
 
-          if [ "$DEPLOYMENT_ID" == "None" ]; then
-            echo "No deployment found."
-            exit 1
-          fi
+      #     if [ "$DEPLOYMENT_ID" == "None" ]; then
+      #       echo "No deployment found."
+      #       exit 1
+      #     fi
 
-          echo "Deployment ID: $DEPLOYMENT_ID"
+      #     echo "Deployment ID: $DEPLOYMENT_ID"
           
-          # Loop to check the deployment status
-          while true; do
-            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
+      #     # Loop to check the deployment status
+      #     while true; do
+      #       STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
 
-            echo "Deployment status: $STATUS"
+      #       echo "Deployment status: $STATUS"
 
-            if [[ "$STATUS" == "Succeeded" ]]; then
-              echo "Deployment succeeded!"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
-              echo "Deployment failed!"
-              exit 1
-            else
-              echo "Deployment is in progress..."
-              sleep 30
-            fi
-          done
+      #       if [[ "$STATUS" == "Succeeded" ]]; then
+      #         echo "Deployment succeeded!"
+      #         break
+      #       elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
+      #         echo "Deployment failed!"
+      #         exit 1
+      #       else
+      #         echo "Deployment is in progress..."
+      #         sleep 30
+      #       fi
+      #     done
