trigger + monitor

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,9 @@
 name: Deploy
 
 on:
-  # push:
-  #   branches:
-  #     - 'blue-green-deploy'
+  push:
+    branches:
+      - 'blue-green-deploy'
   workflow_dispatch:
 
 permissions:
@@ -52,7 +52,6 @@ jobs:
           echo "Extracted project_name: $PROJECT_NAME"
           echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT
 
-      # Step 3: Replace placeholders in the appspec.json file
       - name: Prepare AppSpec File
         run: |
           sed -i 's|{{TASK_VERSION}}|${{ needs.code.outputs.task_definition_revision }}|g' ${{ env.APP_SPEC_FILE }}
@@ -64,7 +63,6 @@ jobs:
       - name: Upload yaml to s3
         run: aws s3 cp ${{ env.APP_SPEC_FILE }} s3://${{ needs.code.outputs.app_specs_bucket}}/${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}
 
-      # Step 4: Create CodeDeploy Deployment
       - name: Create CodeDeploy Deployment
         env:
           APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
@@ -78,41 +76,40 @@ jobs:
             --revision "{\"revisionType\":\"S3\",\"s3Location\":{\"bucket\":\"${{ needs.code.outputs.app_specs_bucket}}\",\"key\":\"${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}\",\"bundleType\":\"YAML\"}}" \
             --region ${{ vars.AWS_REGION }}
 
-      # # Step 5: Monitor Deployment Status
-      # - name: Monitor Deployment Status
-      #   env:
-      #     APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
-      #     GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
-      #   run: |
-      #     echo "Monitoring CodeDeploy deployment status"
-      #     DEPLOYMENT_ID=$(aws deploy list-deployments \
-      #       --application-name "$APP_NAME" \
-      #       --deployment-group-name "$GROUP_NAME" \
-      #       --region ${{ vars.AWS_REGION }} \
-      #       --max-items 1 \
-      #       --query 'deployments[0]' --output text)
+      - name: Monitor Deployment Status
+        env:
+          APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
+          GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
+        run: |
+          echo "Monitoring CodeDeploy deployment status"
+          DEPLOYMENT_ID=$(aws deploy list-deployments \
+            --application-name "$APP_NAME" \
+            --deployment-group-name "$GROUP_NAME" \
+            --region ${{ vars.AWS_REGION }} \
+            --max-items 1 \
+            --query 'deployments[0]' --output text)
 
-      #     if [ "$DEPLOYMENT_ID" == "None" ]; then
-      #       echo "No deployment found."
-      #       exit 1
-      #     fi
+          if [ "$DEPLOYMENT_ID" == "None" ]; then
+            echo "No deployment found."
+            exit 1
+          fi
 
-      #     echo "Deployment ID: $DEPLOYMENT_ID"
+          echo "Deployment ID: $DEPLOYMENT_ID"
           
-      #     # Loop to check the deployment status
-      #     while true; do
-      #       STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
+          # Loop to check the deployment status
+          while true; do
+            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
 
-      #       echo "Deployment status: $STATUS"
+            echo "Deployment status: $STATUS"
 
-      #       if [[ "$STATUS" == "Succeeded" ]]; then
-      #         echo "Deployment succeeded!"
-      #         break
-      #       elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
-      #         echo "Deployment failed!"
-      #         exit 1
-      #       else
-      #         echo "Deployment is in progress..."
-      #         sleep 30
-      #       fi
-      #     done
+            if [[ "$STATUS" == "Succeeded" ]]; then
+              echo "Deployment succeeded!"
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
+              echo "Deployment failed!"
+              exit 1
+            else
+              echo "Deployment is in progress..."
+              sleep 30
+            fi
+          done
