Blue green deploy (#4)
* add blue green tgs

* mv lb to service

* deploy refactor

* destroy refactor

* fix

* data "aws_subnets"

* short name

* rm load_balancer_port var

* mv vpc endpoint to /ecr

* fmt

* type = "CODE_DEPLOY"

* lb_ to output arn

* add checks

* test change

* pass in image tag

* build.yml

* rename

* rm trigger

* trigger on this branch

* fix

* more fixes

* pass image uri

* back to tag

* fix

* most_recent = true

* baaack to uri

* fix

* dummy uri

* nudge

* echo Image:$IMAGE_URI

* debug

* chnge action

* use env

* test

* setup

* fix

* workflow_call

* inputs

* project name var

* vars file

* output

* pass out uri

* -var-file=${{ github.workspace }}/tf/variables.tfvars

* rm env:

* rm repo name var

* pass in codedeploy_app_name var

* kick

* output task_definition_revision

* add deployment to destroy

* rm deploy

* check existing svc

* cluster check

* fix output

* service and network deploy

* mv check to action file

* shell: bash

* pass in codedeploy_group_name var

* rm setup trigger

* create deployment in ci

* ci job order fix

* fix

* add revision as version

* $GITHUB_OUTPUT

* typo

* escape json

* setup

* check for inactive cluster

* rm trigger

* fix

* set id

* set bool in $GITHUB_OUTPUT

* combine

* debug

* case service_exists

* refactor

* task_definition_arn:

* fix code deploy app reference

* fixes + trigger

* pass into env vars

* casing fix?

* file pipe

* json fix

* escapign fix

* app_specs_bucket

* yaml

* refactor

* trigger

* rm "

* escape json

* app_specs_bucket access

* fix

* trigger + monitor

* fix destroy order

* shorten tg name

* trigger deploy

* use target group name

* repo name

* TF_VAR_ecr_repository_name

* trigger

* depl trigger

* codedeploy iams

* deploy

* iam fixes

* get id

* allow code deploy ecs task access

* trig

* minor

* lock down codedeploy iam

* individual policies

* rm l

* elb iam fix

* add task set to iams

* pass in dep config name

* speed up feedback

* fix

* ModifyListener iam for lb

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,283 +1,117 @@
 name: Deploy
 
 on:
-  push:
-    branches:
-      - main
   workflow_dispatch:
-
-env:
-  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
-  aws_region: ${{ vars.AWS_REGION }}
-  aws_role: ${{ vars.AWS_ROLE }}
-
-  TF_VAR_project_name: ${{ github.event.repository.name }}
-  TF_VAR_region: ${{ vars.AWS_REGION }}
-  TF_VAR_private_vpc_name: ecs-private-vpc
-  TF_VAR_api_stage_name: dev
-  TF_VAR_container_port: 3000
-  TF_VAR_load_balancer_port: 80
 
 permissions:
   id-token: write
   contents: read
       
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ env.aws_region }}
-          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
-          role-session-name: GitHubActions
+  code:
+    uses: ./.github/workflows/build.yml
+    with:
+      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
+      aws_region: ${{ vars.AWS_REGION }}
+      aws_role: ${{ vars.AWS_ROLE }}
 
-      - name: Init
-        shell: bash
-        run: |
-          cd tf/ecr
-          terraform init
-    
-      - name: Deploy
-        shell: bash
-        id: deploy
-        run: |
-          cd tf/ecr
-          terraform apply -auto-approve
-
-      - name: Build and push detected changes
-        id: build-image
-        uses: ./.github/actions/build_image
-        with:
-          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
-          aws_region: ${{ vars.AWS_REGION }}
-
-  network:
-    runs-on: ubuntu-latest
-    outputs:
-      lb_security_group_id: ${{ steps.set-envs.outputs.LB_SERCURITY_GROUP_ID }}
-      lb_listener_arn: ${{ steps.set-envs.outputs.LB_LISTENER_ARN }}
-      target_group_arn: ${{ steps.set-envs.outputs.TARGET_GROUP_ARN }}
-      api_invoke_url: ${{ steps.set-envs.outputs.API_INVOKE_URL }}
-      private_vpc_id: ${{ steps.set-envs.outputs.PRIVATE_VPC_ID }}
-      private_subnet_ids: ${{ steps.set-envs.outputs.PRIVATE_SUBNET_IDS }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ env.aws_region }}
-          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
-          role-session-name: GitHubActions
-
-      - name: Init
-        shell: bash
-        run: |
-          cd tf/network
-          terraform init
-    
-      - name: Deploy
-        shell: bash
-        id: deploy
-        run: |
-          cd tf/network
-          terraform apply -auto-approve
-
-      - name: Set env vars
-        id: set-envs
-        shell: bash
-        run: |
-          cd tf/network
-
-          LB_SERCURITY_GROUP_ID=$(terraform output -raw lb_security_group_id)
-          echo "LB_SERCURITY_GROUP_ID=$LB_SERCURITY_GROUP_ID" >> $GITHUB_OUTPUT
-
-          LB_LISTENER_ARN=$(terraform output -raw lb_listener_arn)
-          echo "LB_LISTENER_ARN=$LB_LISTENER_ARN" >> $GITHUB_OUTPUT
-
-          TARGET_GROUP_ARN=$(terraform output -raw target_group_arn)
-          echo "TARGET_GROUP_ARN=$TARGET_GROUP_ARN" >> $GITHUB_OUTPUT
-
-          API_INVOKE_URL=$(terraform output -raw api_invoke_url)
-          echo "API_INVOKE_URL=$API_INVOKE_URL" >> $GITHUB_OUTPUT
-
-          PRIVATE_VPC_ID=$(terraform output -raw private_vpc_id)
-          echo "PRIVATE_VPC_ID=$PRIVATE_VPC_ID" >> $GITHUB_OUTPUT
-
-          PRIVATE_SUBNET_IDS=$(terraform output -json private_subnet_ids)
-          echo "PRIVATE_SUBNET_IDS=$PRIVATE_SUBNET_IDS" >> $GITHUB_OUTPUT
-
-
-  task:
-    needs: build
-    runs-on: ubuntu-latest
-    outputs:
-      task_definition_arn: ${{ steps.set-envs.outputs.TASK_DEFINITION_ARN }}
-      image_uri: ${{ steps.set-envs.outputs.IMAGE_URI }}
-      cloudwatch_log_group: ${{ steps.set-envs.outputs.CLOUDWATCH_LOG_GROUP }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ env.aws_region }}
-          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
-          role-session-name: GitHubActions
-
-      - name: Init
-        shell: bash
-        run: |
-          cd tf/task
-          terraform init
-    
-      - name: Deploy
-        shell: bash
-        id: deploy
-        run: |
-          cd tf/task
-          terraform apply -auto-approve
-
-      - name: Set env vars
-        id: set-envs
-        shell: bash
-        run: |
-          cd tf/task
-
-          TASK_DEFINITION_ARN=$(terraform output -raw task_definition_arn)
-          echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_OUTPUT
-
-          IMAGE_URI=$(terraform output -raw image_uri)
-          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT
-
-          CLOUDWATCH_LOG_GROUP=$(terraform output -raw cloudwatch_log_group)
-          echo "CLOUDWATCH_LOG_GROUP=$CLOUDWATCH_LOG_GROUP" >> $GITHUB_OUTPUT
-
-  service:
-    needs: 
-      - build
-      - task
-      - network
+  deploy:
+    needs: code
     runs-on: ubuntu-latest
     env:
-      TF_VAR_task_definition_arn: ${{ needs.task.outputs.task_definition_arn }}
-      TF_VAR_private_vpc_id: ${{ needs.network.outputs.private_vpc_id }}
-      TF_VAR_private_subnet_ids: ${{ needs.network.outputs.private_subnet_ids }}
-      TF_VAR_lb_target_group_arn: ${{ needs.network.outputs.target_group_arn }}
-      TF_VAR_load_balancer_security_group_id: ${{ needs.network.outputs.lb_security_group_id }}
-    outputs:
-      cluster_name: ${{ steps.set-envs.outputs.CLUSTER_NAME }}
-      service_name: ${{ steps.set-envs.outputs.SERVICE_NAME }}
+      TF_VAR_FILE: tf/variables.tfvars
+      APP_SPEC_FILE: appspec.yaml
     steps:
       - uses: actions/checkout@v4
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
+      - uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-region: ${{ env.aws_region }}
-          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE }}
           role-session-name: GitHubActions
 
-      - name: Init
+      - name: Read code deploy app vars from tfvars file
+        id: read-vars
         shell: bash
         run: |
-          cd tf/service
-          terraform init
-    
-      - name: Deploy
-        shell: bash
-        id: deploy
+          CODE_DEPLOY_APP_NAME=$(grep 'codedeploy_app_name' "${{ env.TF_VAR_FILE }}" | sed 's/.*= "\(.*\)"/\1/')
+          echo "Extracted codedeploy_app_name: $CODE_DEPLOY_APP_NAME"
+          echo "CODE_DEPLOY_APP_NAME=$CODE_DEPLOY_APP_NAME" >> $GITHUB_OUTPUT
+
+          CODE_DEPLOY_GROUP_NAME=$(grep 'codedeploy_group_name' "${{ env.TF_VAR_FILE }}" | sed 's/.*= "\(.*\)"/\1/')
+          echo "Extracted codedeploy_group_name: $CODE_DEPLOY_APP_NAME"
+          echo "CODE_DEPLOY_GROUP_NAME=$CODE_DEPLOY_GROUP_NAME" >> $GITHUB_OUTPUT
+
+          CONTAINER_PORT=$(grep 'container_port' "${{ env.TF_VAR_FILE }}" | sed 's/.*= //')
+          echo "Extracted container_port: $CONTAINER_PORT"
+          echo "CONTAINER_PORT=$CONTAINER_PORT" >> $GITHUB_OUTPUT
+
+          PROJECT_NAME=$(grep 'project_name' "${{ env.TF_VAR_FILE }}" | sed 's/.*= "\(.*\)"/\1/')
+          echo "Extracted project_name: $PROJECT_NAME"
+          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT
+
+          DEPLOYMENT_CONFIG=$(grep 'deployment_config' "${{ env.TF_VAR_FILE }}" | sed 's/.*= "\(.*\)"/\1/')
+          echo "Extracted deployment_confi: $DEPLOYMENT_CONFIG"
+          echo "DEPLOYMENT_CONFIG=$DEPLOYMENT_CONFIG" >> $GITHUB_OUTPUT
+
+      - name: Prepare AppSpec File
         run: |
-          cd tf/service
-          terraform apply -auto-approve
+          sed -i 's|{{TASK_VERSION}}|${{ needs.code.outputs.task_definition_revision }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{TASK_DEFINITION_ARN}}|${{ needs.code.outputs.task_definition_arn }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{CONTAINER_NAME}}|${{ steps.read-vars.outputs.project_name }}|g' ${{ env.APP_SPEC_FILE }}
+          sed -i 's|{{CONTAINER_PORT}}|${{ steps.read-vars.outputs.container_port }}|g' ${{ env.APP_SPEC_FILE }}
+          cat ${{ env.APP_SPEC_FILE }}
 
-      - name: Set env vars
-        id: set-envs
-        shell: bash
+      - name: Upload yaml to s3
+        run: aws s3 cp ${{ env.APP_SPEC_FILE }} s3://${{ needs.code.outputs.app_specs_bucket}}/${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}
+
+      - name: Create CodeDeploy Deployment
+        id: create-deployment
+        env:
+          APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
+          GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
+          DEPLOYMENT_CONFIG: ${{ steps.read-vars.outputs.DEPLOYMENT_CONFIG }}
         run: |
-          cd tf/service
+          echo "Creating CodeDeploy deployment"
+          DEPLOYMENT_OUTPUT=$(aws deploy create-deployment \
+            --application-name "$APP_NAME" \
+            --deployment-group-name "$GROUP_NAME" \
+            --deployment-config-name $DEPLOYMENT_CONFIG \
+            --revision "{\"revisionType\":\"S3\",\"s3Location\":{\"bucket\":\"${{ needs.code.outputs.app_specs_bucket}}\",\"key\":\"${{ needs.code.outputs.task_definition_revision }}-${{ env.APP_SPEC_FILE }}\",\"bundleType\":\"YAML\"}}" \
+            --region ${{ vars.AWS_REGION }})
+          DEPLOYMENT_ID=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.deploymentId')
+          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
 
-          CLUSTER_NAME=$(terraform output -raw cluster_name)
-          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_OUTPUT
-
-          SERVICE_NAME=$(terraform output -raw service_name)
-          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT
-
-  check_image:
-    needs: 
-      - task
-      - service
-    runs-on: ubuntu-latest
-    steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-            aws-region: ${{ env.aws_region }}
-            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
-            role-session-name: GitHubActions
-
-      - name: Get current task definition
-        id: task-def
-        shell: bash
+      - name: Monitor Deployment Status
+        env:
+          APP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_APP_NAME }}
+          GROUP_NAME: ${{ steps.read-vars.outputs.CODE_DEPLOY_GROUP_NAME }}
+          DEPLOYMENT_ID: ${{ steps.create-deployment.outputs.DEPLOYMENT_ID }}
         run: |
-          TASK_DEF_ARN=$(aws ecs describe-services \
-              --cluster ${{ needs.service.outputs.cluster_name }} \
-              --services ${{ needs.service.outputs.service_name }} \
-              --region ${{ env.aws_region }} \
-              --query 'services[0].taskDefinition' \
-              --output text)
-          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
+          echo "Monitoring CodeDeploy deployment status"
 
-      - name: Get image from task definition
-        id: check-image
-        shell: bash
-        run: |
-          CURRENT_IMAGE=$(aws ecs describe-task-definition \
-              --task-definition ${{ env.TASK_DEF_ARN }} \
-              --region ${{ env.aws_region }} \
-              --query 'taskDefinition.containerDefinitions[*].image' \
-              --output text)
-          echo "CURRENT_IMAGE=$CURRENT_IMAGE"
-          echo "CURRENT_IMAGE=$CURRENT_IMAGE" >> $GITHUB_ENV
-
-      - name: Compare with Terraform image
-        id: compare
-        run: |
-          if [ "${{ env.CURRENT_IMAGE }}" != "${{ needs.task.outputs.image_uri }}" ]; then
-            echo "ERROR: Image mismatch! Current image: ${{ env.CURRENT_IMAGE }}, Expected: ${{ needs.task.outputs.image_uri }}"
-            exit 1
-          else
-            echo "Image matched: ${{ env.CURRENT_IMAGE }}"
-          fi
-
-  check_response:
-    needs: 
-      - network
-      - service
-    runs-on: ubuntu-latest
-    steps:
-      - name: Make API request
-        id: curl_request
-        run: |
-          RESPONSE=$(curl -s ${{ needs.network.outputs.api_invoke_url}}/host)
-          echo "Response: $RESPONSE"
-          echo "$RESPONSE" | jq
-      
-      - name: Assert API response contains expected fields
-        run: |
-          RESPONSE=$(curl -s ${{ needs.network.outputs.api_invoke_url}}/host)
-          echo "$RESPONSE" | jq
+          echo "Deployment ID: $DEPLOYMENT_ID"
           
-          # Extract values from response
-          MESSAGE=$(echo "$RESPONSE" | jq -r '.message')
-          IMAGE_URI=$(echo "$RESPONSE" | jq -r '.imageUri')
-          HOSTNAME=$(echo "$RESPONSE" | jq -r '.hostname')
+          # Loop to check the deployment status
+          while true; do
+            DEPLOYMENT_INFO=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo' --output json)
 
-          # Check if expected fields exist
-          if [[ "$MESSAGE" == "null" || "$IMAGE_URI" == "null" || "$HOSTNAME" == "null" ]]; then
-            echo "Error: Response does not contain expected fields."
-            exit 1
-          else
-            echo "API response contains all expected fields."
-          fi
-        
+            STATUS=$(echo $DEPLOYMENT_INFO | jq -r '.status')
+
+            echo "Deployment status: $STATUS"
+
+            if [[ "$STATUS" == "Succeeded" ]]; then
+              echo "Deployment succeeded!"
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
+              ERROR_CODE=$(echo $DEPLOYMENT_INFO | jq -r '.errorInformation.code')
+              ERROR_MESSAGE=$(echo $DEPLOYMENT_INFO | jq -r '.errorInformation.message')
+
+              echo $ERROR_CODE
+              echo $ERROR_MESSAGE
+              echo "Deployment failed!"
+              exit 1
+            else
+              echo "Deployment is in progress..."
+              sleep 10
+            fi
+          done
